services:
  # Next.js 15 приложение
  app:
    image: redguard-server:latest
    build: .
    container_name: redguard-app
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8080:8080"
      - "1080:1080"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - SERVER_ID=${SERVER_ID:-server1}
      - SERVER_HOST=${SERVER_HOST:-localhost}
      - JWT_SECRET=${JWT_SECRET}
      - VPN_SECRET=${VPN_SECRET}
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASS=${PROXY_PASS}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - redis
      - xray
      - proxy
    networks:
      - redguard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Xray VPN сервер
  xray:
    image: ghcr.io/xtls/xray-core:latest
    container_name: redguard-xray
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/xray:/etc/xray
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - redguard-network
    command: ["xray", "-config", "/etc/xray/config.json"]
    healthcheck:
      test: ["CMD", "xray", "version"]
      interval: 30s
      timeout: 10s
      retries: 3

  # HTTP/SOCKS прокси сервер
  proxy:
    image: nginx:alpine
    container_name: redguard-nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "1080:1080"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/proxy:/etc/proxy
    networks:
      - redguard-network
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis для синхронизации между серверами
  redis:
    image: redis:7-alpine
    container_name: redguard-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redguard-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Certbot для автоматических SSL сертификатов
  certbot:
    image: certbot/certbot
    container_name: redguard-certbot
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./config/certbot:/var/lib/letsencrypt
    networks:
      - redguard-network
    command: certonly --webroot --webroot-path=/var/www/html --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${SERVER_HOST} --keep-until-expiring

networks:
  redguard-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis-data:
    driver: local
